export const totaluri = {
  alarmaFalsa: 0,
  alteSU: 0,
  asistentaPersoane: 0,
  deblocareUsa: 0,
  descarcerare: 0,
  evenimentRutier: 0,
  exercitii: 0,
  explozie: 0,
  incendii: 0,
  incendiiDeVegetatie: 0,
  informare: 0,
  inundatii: 0,
  nrMP: 0,
  pirotehnic: 0,
  recunoasteri: 0,
  salvareAnimal: 0,
  smurd: 0,
  verificareATI: 0,
};

export const totaluriSaptamanale = {
  alarmaFalsa: 0,
  alteSU: 0,
  asistentaPersoane: 0,
  deblocareUsa: 0,
  descarcerare: 0,
  evenimentRutier: 0,
  exercitii: 0,
  explozie: 0,
  incendii: 0,
  incendiiDeVegetatie: 0,
  informare: 0,
  inundatii: 0,
  nrMP: 0,
  pirotehnic: 0,
  recunoasteri: 0,
  salvareAnimal: 0,
  smurd: 0,
  verificareATI: 0,
};
